<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\KatalogBarang;
use App\Models\Unit;
use Illuminate\Database\Seeder;

class DryGoodSeeder extends Seeder
{
    public function run(): void
    {
        $dryGood = Category::where('nama', 'Dry Good Grosir Monouse Cleaning')->first();
        if (!$dryGood) {
            $this->command->error('Category "Dry Good Grosir Monouse Cleaning" not found. Run MasterDataSeeder first.');
            return;
        }

        $unitNames = ['KG', 'PACK', 'BTL', 'CTN', 'GLN', 'KLG', 'KRG', 'SLOP', 'BAL', 'PCS', 'CAN', 'ROL', 'PAIL', 'LTR', 'BOX', 'SCT', 'BKS', 'IKAT', 'RTG'];
        foreach ($unitNames as $unitName) {
            Unit::firstOrCreate(['nama' => $unitName]);
        }
        $units = Unit::whereIn('nama', $unitNames)->get()->keyBy('nama');

        $items = [
            ['kode' => 'D001', 'nama' => 'ABC - KECAP ASIN @600ml', 'unit' => 'BTL'],
            ['kode' => 'D002', 'nama' => 'ABC - KECAP MANIS @600gr', 'unit' => 'PACK'],
            ['kode' => 'D003', 'nama' => 'ABC - KECAP MANIS @6kg', 'unit' => 'GLN'],
            ['kode' => 'D004', 'nama' => 'ABC - SAMBAL TERASI @23gr x 10pak (100pcs)', 'unit' => 'CTN'],
            ['kode' => 'D005', 'nama' => 'ABC - SAUS SAMBAL @1kg', 'unit' => 'PACK'],
            ['kode' => 'D006', 'nama' => 'ABC - SAUS SAMBAL @0,5/7kg', 'unit' => 'GLN'],
            ['kode' => 'D007', 'nama' => 'ABC - SAUS SAMBAL SACHET @22sct', 'unit' => 'PACK'],
            ['kode' => 'D008', 'nama' => 'ABC - SAUS SAMBAL SACHET @22sct x 21pak', 'unit' => 'CTN'],
            ['kode' => 'D009', 'nama' => 'ABC - SAUS TIRAM @420ml', 'unit' => 'BTL'],
            ['kode' => 'D010', 'nama' => 'ABC - SAUS TOMAT @1kg', 'unit' => 'PACK'],
            ['kode' => 'D011', 'nama' => 'ABC - SAUS TOMAT @0,5/7kg', 'unit' => 'GLN'],
            ['kode' => 'D012', 'nama' => 'ABC - SAUS TOMAT SACHET @22sct', 'unit' => 'PACK'],
            ['kode' => 'D013', 'nama' => 'ABC - SAUS TOMAT SACHET @22sct x 21pak', 'unit' => 'CTN'],
            ['kode' => 'D014', 'nama' => 'ABON AYAM', 'unit' => 'KG'],
            ['kode' => 'D015', 'nama' => 'ABON SAPI "RATU" @100gr x 10pak', 'unit' => 'KG'],
            ['kode' => 'D016', 'nama' => 'AGAR "SWALLOW" PUTIH @12bks', 'unit' => 'PACK'],
            ['kode' => 'D017', 'nama' => 'AJINOMOTO @1kg', 'unit' => 'PACK'],
            ['kode' => 'D018', 'nama' => 'ALMOND POWDER @100gr', 'unit' => 'PACK'],
            ['kode' => 'D019', 'nama' => 'ALMOND SLICE @100gr', 'unit' => 'PACK'],
            ['kode' => 'D020', 'nama' => 'ALUMINIUM FOIL @300cm', 'unit' => 'PACK'],
            ['kode' => 'D021', 'nama' => 'ALUMINIUM FOIL @450cm', 'unit' => 'PACK'],
            ['kode' => 'D022', 'nama' => 'ANGGUR @600ml', 'unit' => 'BTL'],
            ['kode' => 'D023', 'nama' => 'ANISTAR / BUNGA LAWANG', 'unit' => 'KG'],
            ['kode' => 'D024', 'nama' => 'AQUA @240ml x 48pcs', 'unit' => 'CTN'],
            ['kode' => 'D025', 'nama' => 'AQUA @330ml x 24pcs', 'unit' => 'CTN'],
            ['kode' => 'D026', 'nama' => 'AQUA @600ml x 24pcs', 'unit' => 'CTN'],
            ['kode' => 'D027', 'nama' => 'ARANG KAYU', 'unit' => 'KRG'],
            ['kode' => 'D028', 'nama' => 'ASEM JAWA @350gr', 'unit' => 'PACK'],
            ['kode' => 'D029', 'nama' => 'ASPARAGUS @430gr', 'unit' => 'KLG'],
            ['kode' => 'D030', 'nama' => 'BAKED BEAN "AYAM BRAND" @425gr', 'unit' => 'KLG'],
            ['kode' => 'D031', 'nama' => 'BAKERINE PLUS @500gr / S 500IMPROVER', 'unit' => 'PACK'],
            ['kode' => 'D032', 'nama' => 'BAKING POWDER "HERCULES" @450gr', 'unit' => 'KLG'],
            ['kode' => 'D033', 'nama' => 'BLUE BAND @200gr', 'unit' => 'PACK'],
            ['kode' => 'D034', 'nama' => 'BAWANG GORENG (BIASA)', 'unit' => 'KG'],
            ['kode' => 'D035', 'nama' => 'BAWANG GORENG (SUPER) @200gr', 'unit' => 'PACK'],
            ['kode' => 'D036', 'nama' => 'BAY CLEAN @1ltr', 'unit' => 'BTL'],
            ['kode' => 'D037', 'nama' => 'BBQ SAUCE "DELMONTE" @330gr', 'unit' => 'BTL'],
            ['kode' => 'D038', 'nama' => 'BEEF CORNET "PRONAS"', 'unit' => 'CAN'],
            ['kode' => 'D039', 'nama' => 'BERAS KETAN HITAM', 'unit' => 'KG'],
            ['kode' => 'D040', 'nama' => 'BERAS KETAN PUTIH', 'unit' => 'KG'],
            ['kode' => 'D041', 'nama' => 'BERAS MERAH', 'unit' => 'KG'],
            ['kode' => 'D042', 'nama' => 'BOX 18 X 18', 'unit' => 'PCS'],
            ['kode' => 'D043', 'nama' => 'BIHUN JAGUNG "PADAMU"', 'unit' => 'PACK'],
            ['kode' => 'D044', 'nama' => 'BIHUN JAGUNG "PADAMU" @12bks', 'unit' => 'BAL'],
            ['kode' => 'D045', 'nama' => 'BIHUN SUPER "AAA" @450gr', 'unit' => 'PACK'],
            ['kode' => 'D046', 'nama' => 'BIJI PALA', 'unit' => 'KG'],
            ['kode' => 'D047', 'nama' => 'BIJI WIJEN HITAM', 'unit' => 'KG'],
            ['kode' => 'D048', 'nama' => 'BIJI WIJEN PUTIH', 'unit' => 'KG'],
            ['kode' => 'D049', 'nama' => 'BISKUIT REGAL @230gr', 'unit' => 'PACK'],
            ['kode' => 'D050', 'nama' => 'BLUE BAND @15kg', 'unit' => 'CTN'],
            ['kode' => 'D051', 'nama' => 'BLUE BAND @2kg', 'unit' => 'KLG'],
            ['kode' => 'D052', 'nama' => 'BOX 12 X 16', 'unit' => 'PCS'],
            ['kode' => 'D053', 'nama' => 'BOX 20 X 20', 'unit' => 'PCS'],
            ['kode' => 'D054', 'nama' => 'BOX 20 X 20 + MICA SEKAT', 'unit' => 'PCS'],
            ['kode' => 'D055', 'nama' => 'BOX BENTO HITAM "SPATRA"', 'unit' => 'PCS'],
            ['kode' => 'D056', 'nama' => 'BUMBU PECEL "SINTI" @100gr', 'unit' => 'PACK'],
            ['kode' => 'D057', 'nama' => 'BUMBU PECEL "SINTI" @100gr x 60pack', 'unit' => 'CTN'],
            ['kode' => 'D058', 'nama' => 'BUTTER POTION "ANCOR" @7gr', 'unit' => 'PCS'],
            ['kode' => 'D059', 'nama' => 'CANDY/PERMENT MIX VARIAN', 'unit' => 'PACK'],
            ['kode' => 'D060', 'nama' => 'CENGKEH UTUH', 'unit' => 'KG'],
            ['kode' => 'D061', 'nama' => 'CHOCO CHIPS @250gr', 'unit' => 'PACK'],
            ['kode' => 'D062', 'nama' => 'COCA-COLA @1,000ml', 'unit' => 'BTL'],
            ['kode' => 'D063', 'nama' => 'COCA-COLA @250ml', 'unit' => 'KLG'],
            ['kode' => 'D064', 'nama' => 'COCOA "VAN HOUTEN" @165gr', 'unit' => 'PACK'],
            ['kode' => 'D065', 'nama' => 'COKLAT "COLATA" DARK @1kg', 'unit' => 'PACK'],
            ['kode' => 'D066', 'nama' => 'COKLAT "COLATA" WHITE @1kg', 'unit' => 'PACK'],
            ['kode' => 'D067', 'nama' => 'COKLAT "MEISES" CERES @225gr', 'unit' => 'PACK'],
            ['kode' => 'D068', 'nama' => 'COKLAT MILO @990gr', 'unit' => 'PACK'],
            ['kode' => 'D069', 'nama' => 'COKLAT CERES CURAH @1kg', 'unit' => 'PACK'],
            ['kode' => 'D070', 'nama' => 'CHOCO POP @300gr', 'unit' => 'PACK'],
            ['kode' => 'D071', 'nama' => 'COOKING CREAM "MASTER GOVERMET" @1000ml', 'unit' => 'PACK'],
            ['kode' => 'D072', 'nama' => 'COOKING CREAM "MILAC GOLD" @1ltr', 'unit' => 'PACK'],
            ['kode' => 'D073', 'nama' => 'CREAMER SACHET @250bks', 'unit' => 'BAL'],
            ['kode' => 'D074', 'nama' => 'CUKA "DJX" @650ml', 'unit' => 'BTL'],
            ['kode' => 'D075', 'nama' => 'CERES WARNA-WARNI @250gr', 'unit' => 'PACK'],
            ['kode' => 'D076', 'nama' => 'CREAKER CREAM "KHONG GUAN" @300gr', 'unit' => 'PACK'],
            ['kode' => 'D077', 'nama' => 'EMPING MELINJO', 'unit' => 'KG'],
            ['kode' => 'D078', 'nama' => 'FANTA @250ml', 'unit' => 'KLG'],
            ['kode' => 'D079', 'nama' => 'FERIMPAN BROWN @500gr', 'unit' => 'PACK'],
            ['kode' => 'D080', 'nama' => 'FRUIT COCKTAIL "DELMonte" @825gr', 'unit' => 'KLG'],
            ['kode' => 'D081', 'nama' => 'FIGARO - BLACK OLIVE @450gr', 'unit' => 'BTL'],
            ['kode' => 'D082', 'nama' => 'FIGARO - CAPOET/CAPERS @450gr', 'unit' => 'BTL'],
            ['kode' => 'D083', 'nama' => 'FIGARO - GREEN OLIVE @450gr', 'unit' => 'BTL'],
            ['kode' => 'D084', 'nama' => 'GARAM "DOLPIN" @1kg', 'unit' => 'PACK'],
            ['kode' => 'D085', 'nama' => 'GARAM "DOLPIN" @500gr', 'unit' => 'PACK'],
            ['kode' => 'D086', 'nama' => 'GARAM @250gr', 'unit' => 'PACK'],
            ['kode' => 'D087', 'nama' => "GARPU MAKAN BENING @25'S", 'unit' => 'PACK'],
            ['kode' => 'D088', 'nama' => 'GAS PORTABLE', 'unit' => 'KLG'],
            ['kode' => 'D089', 'nama' => 'GELAS KERTAS KOPI @50pcs', 'unit' => 'SLOP'],
            ['kode' => 'D090', 'nama' => 'GELAS PLASTIK 10oz @50pcs', 'unit' => 'SLOP'],
            ['kode' => 'D091', 'nama' => 'GELAS PLASTIK 12oz @50pcs', 'unit' => 'SLOP'],
            ['kode' => 'D092', 'nama' => 'GELAS PLASTIK 14oz @50pcs', 'unit' => 'SLOP'],
            ['kode' => 'D093', 'nama' => 'GELAS PLASTIK 16oz @50pcs', 'unit' => 'SLOP'],
            ['kode' => 'D094', 'nama' => 'GELAS PLASTIK AQUA 220ML @50pcs', 'unit' => 'SLOP'],
            ['kode' => 'D095', 'nama' => 'GELAS PLASTIK PUDING + TUTUP @50pcs', 'unit' => 'SLOP'],
            ['kode' => 'D096', 'nama' => 'GARAM REFINA (40 X 250gr)', 'unit' => 'BAL'],
            ['kode' => 'D097', 'nama' => "GARAM SACHET (0,5gr X 250'S)", 'unit' => 'BAL'],
            ['kode' => 'D098', 'nama' => 'GULA AREN CAIR "MOLA" @1ltr', 'unit' => 'BTL'],
            ['kode' => 'D099', 'nama' => 'GHERKINS "KOLEMAN" @720gr', 'unit' => 'BTL'],
            ['kode' => 'D100', 'nama' => 'Frozen - GOLDEN FARM - CORN KERNEL @1kg', 'unit' => 'PACK'],
            ['kode' => 'D101', 'nama' => 'Frozen - GOLDEN FARM - FF CRINKLE CUT @1kg', 'unit' => 'PACK'],
            ['kode' => 'D102', 'nama' => 'Frozen - GOLDEN FARM - FF STRAIGHT CUT @1kg', 'unit' => 'PACK'],
            ['kode' => 'D103', 'nama' => 'Frozen - GOLDEN FARM - GREEN PEAS @1kg', 'unit' => 'PACK'],
            ['kode' => 'D104', 'nama' => 'Frozen - GOLDEN FARM - MIX VEGETABLE @1kg', 'unit' => 'PACK'],
            ['kode' => 'D105', 'nama' => 'GULA AREN LOKAL', 'unit' => 'KG'],
            ['kode' => 'D106', 'nama' => 'GULA HALUS "CLARIS" @250gr', 'unit' => 'PACK'],
            ['kode' => 'D107', 'nama' => 'GULA MERAH', 'unit' => 'KG'],
            ['kode' => 'D108', 'nama' => 'GULA PASIR SACHET @250sct x 8gr', 'unit' => 'BAL'],
            ['kode' => 'D109', 'nama' => 'GULA PUTIH @50kg', 'unit' => 'BAL'],
            ['kode' => 'D110', 'nama' => 'GULA PUTIH CURAH @1kg', 'unit' => 'KG'],
            ['kode' => 'D111', 'nama' => 'GULA PUTIH KEMASAN @1kg', 'unit' => 'KG'],
            ['kode' => 'D112', 'nama' => 'HAND GLOVE PLASTIK @100pcs', 'unit' => 'PACK'],
            ['kode' => 'D113', 'nama' => 'HEINZ TOMATO PASTE @3,15kg', 'unit' => 'KLG'],
            ['kode' => 'D114', 'nama' => 'ICING SUGAR @450gr', 'unit' => 'PACK'],
            ['kode' => 'D115', 'nama' => 'AJINOMOTO @500gr', 'unit' => 'PACK'],
            ['kode' => 'D116', 'nama' => 'INDOMIE AYAM BAWANG @40bks', 'unit' => 'CTN'],
            ['kode' => 'D117', 'nama' => 'INDOMIE GORENG @40bks', 'unit' => 'CTN'],
            ['kode' => 'D118', 'nama' => 'INDOMIE KARI AYAM @40bks', 'unit' => 'CTN'],
            ['kode' => 'D119', 'nama' => 'INDOMIE SOTO @40bks', 'unit' => 'CTN'],
            ['kode' => 'D120', 'nama' => 'JAGUNG KALENG "DELMONTE" @432gr (WHOLE)', 'unit' => 'KLG'],
            ['kode' => 'D121', 'nama' => 'JINTEN BUBUK', 'unit' => 'KG'],
            ['kode' => 'D122', 'nama' => 'JAMUR KUPING KERING', 'unit' => 'KG'],
            ['kode' => 'D123', 'nama' => 'JAMUR SHITAKE KERING', 'unit' => 'KG'],
            ['kode' => 'D124', 'nama' => "JAY'S - BASIL LEAVE @20gr", 'unit' => 'BTL'],
            ['kode' => 'D125', 'nama' => "JAY'S - BAY LEAVE @8gr", 'unit' => 'BTL'],
            ['kode' => 'D126', 'nama' => "JAY'S - CHINAMON GROUND @75gr", 'unit' => 'BTL'],
            ['kode' => 'D127', 'nama' => "JAY'S - GARLIC POWDER @80gr", 'unit' => 'BTL'],
            ['kode' => 'D128', 'nama' => "JAY'S - PARSLEY FLAKE @20gr", 'unit' => 'BTL'],
            ['kode' => 'D129', 'nama' => "JAY'S - OREGANO LEAVE @25gr", 'unit' => 'BTL'],
            ['kode' => 'D130', 'nama' => "JAY'S - PAPRIKA POWDER @70gr", 'unit' => 'BTL'],
            ['kode' => 'D131', 'nama' => "JAY'S - ROSEMARY LEAVE @40gr", 'unit' => 'BTL'],
            ['kode' => 'D132', 'nama' => "JAY'S - THYME LEAVE @27gr", 'unit' => 'BTL'],
            ['kode' => 'D133', 'nama' => 'KALDU JAMUR "TOTOLE" @400gr', 'unit' => 'PACK'],
            ['kode' => 'D134', 'nama' => 'JINTEN UTUH', 'unit' => 'KG'],
            ['kode' => 'D135', 'nama' => 'JUS SUNQUICK @2ltr', 'unit' => 'BTL'],
            ['kode' => 'D136', 'nama' => 'KACANG HIJAU', 'unit' => 'KG'],
            ['kode' => 'D137', 'nama' => 'KACANG KEDELAI', 'unit' => 'KG'],
            ['kode' => 'D138', 'nama' => 'KACANG MEDE MENTAH', 'unit' => 'KG'],
            ['kode' => 'D139', 'nama' => 'KACANG MERAH KERING', 'unit' => 'KG'],
            ['kode' => 'D140', 'nama' => 'KERUPUK UDANG "FINNA" NUSANTARA @380gr', 'unit' => 'PACK'],
            ['kode' => 'D141', 'nama' => 'KACANG TANAH', 'unit' => 'KG'],
            ['kode' => 'D142', 'nama' => 'KACANG TANAH KUPAS KULIT ARI', 'unit' => 'KG'],
            ['kode' => 'D143', 'nama' => 'KACANG TOLO', 'unit' => 'KG'],
            ['kode' => 'D144', 'nama' => 'KAPULAGA', 'unit' => 'KG'],
            ['kode' => 'D145', 'nama' => 'KARET GELANG @100gr', 'unit' => 'PACK'],
            ['kode' => 'D146', 'nama' => 'KAYU MANIS', 'unit' => 'KG'],
            ['kode' => 'D147', 'nama' => 'KECAP IKAN "ROYAL GOLD" @600ml', 'unit' => 'BTL'],
            ['kode' => 'D148', 'nama' => 'KECAP IKAN "TJOE HOA" @650ml', 'unit' => 'BTL'],
            ['kode' => 'D149', 'nama' => 'KECAP INGGRIS @620ml', 'unit' => 'BTL'],
            ['kode' => 'D150', 'nama' => 'KECAP MANIS "BANGO" @6,2kg', 'unit' => 'GLN'],
            ['kode' => 'D151', 'nama' => 'KEJU "KRAFT" CHEDDAR @180gr', 'unit' => 'PACK'],
            ['kode' => 'D152', 'nama' => 'KEJU "KRAFT" CHEDDAR @2kg', 'unit' => 'PACK'],
            ['kode' => 'D153', 'nama' => 'KEJU "KRAFT" SLICE', 'unit' => 'PACK'],
            ['kode' => 'D154', 'nama' => 'KELABET', 'unit' => 'KG'],
            ['kode' => 'D155', 'nama' => "KELLOGG'S - FROOT LOOPS @300gr", 'unit' => 'PACK'],
            ['kode' => 'D156', 'nama' => 'KETUMBAR BUBUK', 'unit' => 'KG'],
            ['kode' => 'D157', 'nama' => 'KEMBANG TAHU @100gr', 'unit' => 'PACK'],
            ['kode' => 'D158', 'nama' => 'KEMIRI BELAH', 'unit' => 'KG'],
            ['kode' => 'D159', 'nama' => 'KEMIRI BULAT UTUH', 'unit' => 'KG'],
            ['kode' => 'D160', 'nama' => 'KERTAS MUFFIN', 'unit' => 'ROL'],
            ['kode' => 'D161', 'nama' => 'KERTAS NASI COKLAT @250lbr', 'unit' => 'PACK'],
            ['kode' => 'D162', 'nama' => 'KERTAS NASI KFC @100lbr', 'unit' => 'PACK'],
            ['kode' => 'D163', 'nama' => 'KERTAS ROTI', 'unit' => 'ROL'],
            ['kode' => 'D164', 'nama' => 'KERUPUK "KERECEK KULIT" @500gr', 'unit' => 'PACK'],
            ['kode' => 'D165', 'nama' => 'KERUPUK "NUSANTARA" MERAH @4,8kg', 'unit' => 'BAL'],
            ['kode' => 'D166', 'nama' => 'KERUPUK "NUSANTARA" PUTIH @4,8kg', 'unit' => 'BAL'],
            ['kode' => 'D167', 'nama' => 'KERUPUK BAWANG (BELANG)', 'unit' => 'KG'],
            ['kode' => 'D168', 'nama' => 'KERUPUK BAWANG (BELANG) @3kg', 'unit' => 'BAL'],
            ['kode' => 'D169', 'nama' => 'KERUPUK IKAN', 'unit' => 'KG'],
            ['kode' => 'D170', 'nama' => 'KERUPUK MAWAR KUNING @5kg', 'unit' => 'BAL'],
            ['kode' => 'D171', 'nama' => 'KERUPUK MAWAR PUTIH @5kg', 'unit' => 'BAL'],
            ['kode' => 'D172', 'nama' => 'KERUPUK MERAH (GADO-GADO)', 'unit' => 'KG'],
            ['kode' => 'D173', 'nama' => 'KERUPUK MERAH (GADO-GADO) @3kg', 'unit' => 'BAL'],
            ['kode' => 'D208', 'nama' => 'LAFONTE - LASAGNA @230gr', 'unit' => 'PACK'],
            ['kode' => 'D209', 'nama' => 'LAFONTE - SPAGHETTI @450gr', 'unit' => 'PACK'],
            ['kode' => 'D210', 'nama' => 'LEA AND PERRIN @290gr', 'unit' => 'BTL'],
            ['kode' => 'D211', 'nama' => 'LENGKENG KALENG @565gr', 'unit' => 'KLG'],
            ['kode' => 'D212', 'nama' => 'LYCHEE KALENG @565gr', 'unit' => 'KLG'],
            ['kode' => 'D213', 'nama' => 'MADDRAS CURRY WANG FU @450gr', 'unit' => 'BTL'],
            ['kode' => 'D214', 'nama' => 'MADU CAIR "MADURASA" @910ml', 'unit' => 'BTL'],
            ['kode' => 'D215', 'nama' => 'MADU NUSANTARA @650ml', 'unit' => 'BTL'],
            ['kode' => 'D216', 'nama' => 'MAKARONI SEDANI @1kg', 'unit' => 'KG'],
            ['kode' => 'D217', 'nama' => 'MAMA LEMON @800ml', 'unit' => 'PACK'],
            ['kode' => 'D218', 'nama' => 'MAPLE SYRUP (country kitchen) @710ml', 'unit' => 'BTL'],
            ['kode' => 'D219', 'nama' => 'MARSHMELLOW "MEGA" @300gr', 'unit' => 'PACK'],
            ['kode' => 'D220', 'nama' => 'MASAKO AYAM @250gr', 'unit' => 'PACK'],
            ['kode' => 'D221', 'nama' => 'MASAKO SAPI @250gr', 'unit' => 'PACK'],
            ['kode' => 'D222', 'nama' => 'MAX CREAMER @500gr', 'unit' => 'PACK'],
            ['kode' => 'D223', 'nama' => 'MAYONAISE "HELLMEN\'S" @3000ml', 'unit' => 'PAIL'],
            ['kode' => 'D224', 'nama' => 'MAYONAISE "MAESTRO" @1kg', 'unit' => 'PACK'],
            ['kode' => 'D225', 'nama' => 'MAYONAISE "MAESTRO" @3000ml', 'unit' => 'PAIL'],
            ['kode' => 'D226', 'nama' => 'MENTEGA PUTIH', 'unit' => 'KG'],
            ['kode' => 'D227', 'nama' => 'MICIN SAA @1kg', 'unit' => 'PACK'],
            ['kode' => 'D228', 'nama' => 'MIE TELUR "3 AYAM" @20bks', 'unit' => 'CTN'],
            ['kode' => 'D229', 'nama' => 'MIE TELUR "AA" KERITING @20bks', 'unit' => 'CTN'],
            ['kode' => 'D230', 'nama' => 'MIE TELUR "ATOM BULAN" @200gr', 'unit' => 'PACK'],
            ['kode' => 'D231', 'nama' => 'MIE TELUR "ATOM BULAN" @20bks', 'unit' => 'CTN'],
            ['kode' => 'D232', 'nama' => 'MIKA 20 X 20', 'unit' => 'PCS'],
            ['kode' => 'D233', 'nama' => 'MIKA THWINWALL @1000ML X 25pcs', 'unit' => 'PACK'],
            ['kode' => 'D234', 'nama' => 'MIKA THWINWALL @1500ML X 25pcs', 'unit' => 'PACK'],
            ['kode' => 'D235', 'nama' => 'MIKA THWINWALL @2000ML X 25pcs', 'unit' => 'PACK'],
            ['kode' => 'D236', 'nama' => 'MIKA THWINWALL @200ML X 25pcs', 'unit' => 'PACK'],
            ['kode' => 'D237', 'nama' => 'MIKA THWINWALL @300ML X 25pcs', 'unit' => 'PACK'],
            ['kode' => 'D238', 'nama' => 'MIKA THWINWALL @450ML X 25pcs', 'unit' => 'PACK'],
            ['kode' => 'D239', 'nama' => 'MIKA THWINWALL @500ML X 25pcs', 'unit' => 'PACK'],
            ['kode' => 'D240', 'nama' => 'MIKA THWINWALL @750ML X 25pcs', 'unit' => 'PACK'],
            ['kode' => 'D241', 'nama' => 'MINYAK GORENG "BIMOLI" @18ltr', 'unit' => 'GLN'],
            ['kode' => 'D242', 'nama' => 'MINYAK GR "FORTUNE/SANIA" @2ltr', 'unit' => 'PACK'],
            ['kode' => 'D174', 'nama' => 'KERUPUK MERAH (PADANG) @2,5KG', 'unit' => 'BAL'],
            ['kode' => 'D175', 'nama' => 'KERUPUK PUTIH', 'unit' => 'KG'],
            ['kode' => 'D176', 'nama' => 'KERUPUK PUTIH @3kg', 'unit' => 'BAL'],
            ['kode' => 'D177', 'nama' => 'KERUPUK UDANG "2 GAJAH" @250gr', 'unit' => 'PACK'],
            ['kode' => 'D178', 'nama' => 'KERUPUK UDANG (BESAR)', 'unit' => 'KG'],
            ['kode' => 'D179', 'nama' => 'KERUPUK UDANG (BESAR) @5kg', 'unit' => 'CTN'],
            ['kode' => 'D180', 'nama' => 'KERUPUK UDANG "OBOR MAS"', 'unit' => 'KG'],
            ['kode' => 'D181', 'nama' => 'KERUPUK UDANG "OBOR MAS" @5kg', 'unit' => 'CTN'],
            ['kode' => 'D182', 'nama' => 'KETUMBAR UTUH', 'unit' => 'KG'],
            ['kode' => 'D183', 'nama' => 'KISMIS / RAISIN', 'unit' => 'KG'],
            ['kode' => 'D184', 'nama' => 'KNORR - BBQ SAUCE @1kg', 'unit' => 'PAIL'],
            ['kode' => 'D185', 'nama' => 'KNORR - BEEF POWDER @1kg', 'unit' => 'PACK'],
            ['kode' => 'D186', 'nama' => 'KNORR - CHICKEN POWDER @1kg', 'unit' => 'PACK'],
            ['kode' => 'D187', 'nama' => 'KNORR - DEMIGLACE SC @1kg', 'unit' => 'PAIL'],
            ['kode' => 'D188', 'nama' => 'KOPI KAPAL API "SPECIAL" @380gr', 'unit' => 'PACK'],
            ['kode' => 'D189', 'nama' => 'KNORR - TOM YAM PASTE @1,5kg', 'unit' => 'PAIL'],
            ['kode' => 'D190', 'nama' => 'KNORR - TOMATO FRONTO @2kg', 'unit' => 'KLG'],
            ['kode' => 'D191', 'nama' => 'KOEPOE" - BAKING POWDER', 'unit' => 'BTL'],
            ['kode' => 'D192', 'nama' => 'KOEPOE" - BIJI SELASIH', 'unit' => 'BTL'],
            ['kode' => 'D193', 'nama' => 'KOEPOE" - JINTEN BUBUK', 'unit' => 'BTL'],
            ['kode' => 'D194', 'nama' => 'KOEPOE" - KAYU MANIS BUBUK', 'unit' => 'BTL'],
            ['kode' => 'D195', 'nama' => 'KOEPOE" - SODA KUE', 'unit' => 'BTL'],
            ['kode' => 'D196', 'nama' => 'KOEPOE" - SP', 'unit' => 'BTL'],
            ['kode' => 'D197', 'nama' => 'KOEPOE" - TBM', 'unit' => 'BTL'],
            ['kode' => 'D198', 'nama' => 'KOPI "KAPAL API" @150gr', 'unit' => 'PACK'],
            ['kode' => 'D199', 'nama' => 'KOPI "KAPAL API" @380gr SILVER', 'unit' => 'PACK'],
            ['kode' => 'D200', 'nama' => 'KOPI "KAPAL API" SPECIAL MIX', 'unit' => 'CTN'],
            ['kode' => 'D201', 'nama' => 'KUNYIT BUBUK', 'unit' => 'KG'],
            ['kode' => 'D202', 'nama' => 'KWEPIE DRESSING WIJEN @1ltr', 'unit' => 'BTL'],
            ['kode' => 'D203', 'nama' => 'KWETIAU KERING "WALET" @200gr', 'unit' => 'PACK'],
            ['kode' => 'D204', 'nama' => 'KWETIAU KERING "WALET" @30bks x 200gr', 'unit' => 'CTN'],
            ['kode' => 'D205', 'nama' => 'LADA HITAM UTUH', 'unit' => 'KG'],
            ['kode' => 'D206', 'nama' => 'LADA PUTIH BUBUK NO.2', 'unit' => 'KG'],
            ['kode' => 'D207', 'nama' => 'LADA PUTIH UTUH', 'unit' => 'KG'],
            ['kode' => 'D243', 'nama' => 'MINYAK GORENG @12ltr "MINYAKITA"', 'unit' => 'CTN'],
            ['kode' => 'D244', 'nama' => 'MINYAK GORENG @1ltr "MINYAKITA"', 'unit' => 'LTR'],
            ['kode' => 'D245', 'nama' => 'MINYAK GR "FORTUNE/SANIA" @2ltr x 6pak', 'unit' => 'CTN'],
            ['kode' => 'D246', 'nama' => 'MINYAK IKAN "FISH GRAVY"', 'unit' => 'KLG'],
            ['kode' => 'D247', 'nama' => 'MINYAK WIJEN / SESAME OIL @600ml', 'unit' => 'BTL'],
            ['kode' => 'D248', 'nama' => 'MORIN - PORTION BLUEBERRY JM 12X14X14gr', 'unit' => 'BOX'],
            ['kode' => 'D249', 'nama' => 'MORIN - PORTION NANAS JM 12X14X14gr', 'unit' => 'BOX'],
            ['kode' => 'D250', 'nama' => 'MORIN - PORTION STRAWBERRY JM 12X14X14gr', 'unit' => 'BOX'],
            ['kode' => 'D251', 'nama' => 'MORIN - SELAI BLUEBERRY @2kg', 'unit' => 'PACK'],
            ['kode' => 'D252', 'nama' => 'MORIN - SELAI COKLAT @2kg', 'unit' => 'PACK'],
            ['kode' => 'D253', 'nama' => 'MORIN - SELAI KACANG @2kg', 'unit' => 'PACK'],
            ['kode' => 'D254', 'nama' => 'MORIN - SELAI NANAS @2kg', 'unit' => 'PACK'],
            ['kode' => 'D255', 'nama' => 'MORIN - SELAI SRIKAYA @2kg', 'unit' => 'PACK'],
            ['kode' => 'D256', 'nama' => 'MORIN - SELAI STRAWBERRY @2kg', 'unit' => 'PACK'],
            ['kode' => 'D257', 'nama' => 'MUSHROOM CAMPIGNON KALENG @425gr', 'unit' => 'KLG'],
            ['kode' => 'D258', 'nama' => 'MUSHROOM SOY SAUCE', 'unit' => 'BTL'],
            ['kode' => 'D259', 'nama' => 'MUTIARA SAGU', 'unit' => 'KG'],
            ['kode' => 'D260', 'nama' => 'NATA DE COCO (dadu) @1kg', 'unit' => 'PACK'],
            ['kode' => 'D261', 'nama' => 'NESCAFE - CLASSIC @2gr', 'unit' => 'SCT'],
            ['kode' => 'D262', 'nama' => 'NESCAFE - CLASSIC @2gr x 60sct', 'unit' => 'PACK'],
            ['kode' => 'D263', 'nama' => 'NESCAFE - CLASSIC BUBUK @100gr', 'unit' => 'BTL'],
            ['kode' => 'D264', 'nama' => 'NESTLE - CORN FLAKE @150gr', 'unit' => 'PACK'],
            ['kode' => 'D265', 'nama' => 'NESTLE - HONEY STAR @300gr', 'unit' => 'PACK'],
            ['kode' => 'D266', 'nama' => 'NESTLE - KOKO KRUNCH @300gr', 'unit' => 'PACK'],
            ['kode' => 'D267', 'nama' => 'NUTRIJEL - KECIL (coklat) @10gr x 12bks', 'unit' => 'PACK'],
            ['kode' => 'D268', 'nama' => 'NUTRIJEL - KECIL = RASA @10gr x 12bks', 'unit' => 'PACK'],
            ['kode' => 'D269', 'nama' => 'NUTRIJEL - PUDING COKLAT', 'unit' => 'PACK'],
            ['kode' => 'D270', 'nama' => 'NUTRIJEL - PUDING MANGGA', 'unit' => 'PACK'],
            ['kode' => 'D271', 'nama' => 'NUTRIJEL - PUDING STRAWBERRY', 'unit' => 'PACK'],
            ['kode' => 'D272', 'nama' => 'NUTRIJEL - PUDING VANILA', 'unit' => 'PACK'],
            ['kode' => 'D273', 'nama' => 'OAT MEAL @800gr', 'unit' => 'PACK'],
            ['kode' => 'D274', 'nama' => 'OLIVE OIL "BERTOLI" @1000ml', 'unit' => 'BTL'],
            ['kode' => 'D275', 'nama' => 'OLIVE OIL "PIETRO CORICELI" @250ml', 'unit' => 'BTL'],
            ['kode' => 'D276', 'nama' => 'OREO', 'unit' => 'PACK'],
            ['kode' => 'D277', 'nama' => 'PALM SUGAR @200gr', 'unit' => 'PACK'],
            ['kode' => 'D278', 'nama' => 'PASTA 30ml = RASA (....)', 'unit' => 'BTL'],
            ['kode' => 'D279', 'nama' => 'PAYA TENDERIZER @70gr', 'unit' => 'BTL'],
            ['kode' => 'D280', 'nama' => 'PEACH HELVES "DELMONTE" @825gr', 'unit' => 'KLG'],
            ['kode' => 'D281', 'nama' => 'PEWARNA MAKANAN (....)', 'unit' => 'BTL'],
            ['kode' => 'D282', 'nama' => 'PLASTIK 1 KG (15 X 30) @1kg', 'unit' => 'PACK'],
            ['kode' => 'D283', 'nama' => 'PLASTIK 1/2 KG (12 X 25) @1kg', 'unit' => 'PACK'],
            ['kode' => 'D284', 'nama' => 'PLASTIK 1/4 KG (10 X 20) @1kg', 'unit' => 'PACK'],
            ['kode' => 'D285', 'nama' => 'PLASTIK 2 KG (20 X 35) @1kg', 'unit' => 'PACK'],
            ['kode' => 'D286', 'nama' => 'PLASTIK 30 X 45 "TOMAT" @500gr', 'unit' => 'PACK'],
            ['kode' => 'D287', 'nama' => 'PLASTIK 40 X 60 "TOMAT" @500gr', 'unit' => 'PACK'],
            ['kode' => 'D288', 'nama' => 'PLASTIK 50 X 75 "TOMAT" @500gr', 'unit' => 'PACK'],
            ['kode' => 'D289', 'nama' => 'PLASTIK KRESEK MERAH (CANDI) @40cm', 'unit' => 'PACK'],
            ['kode' => 'D290', 'nama' => 'PLASTIK KRESEK PUTIH @17cm', 'unit' => 'PACK'],
            ['kode' => 'D291', 'nama' => 'PLASTIK KRESEK PUTIH @24cm', 'unit' => 'PACK'],
            ['kode' => 'D292', 'nama' => 'PLASTIK KRESEK PUTIH @28cm', 'unit' => 'PACK'],
            ['kode' => 'D293', 'nama' => 'PLASTIK KRESEK PUTIH @35cm', 'unit' => 'PACK'],
            ['kode' => 'D294', 'nama' => 'PLASTIK KRESEK PUTIH @40cm', 'unit' => 'PACK'],
            ['kode' => 'D295', 'nama' => 'PLASTIK KRESEK PUTIH @50cm', 'unit' => 'PACK'],
            ['kode' => 'D296', 'nama' => 'PLASTIK PP 40 X 60 TRANSPARANT @500gr', 'unit' => 'PACK'],
            ['kode' => 'D297', 'nama' => 'PLASTIK PP 60 X 100 TRANSPARANT @500gr', 'unit' => 'PACK'],
            ['kode' => 'D298', 'nama' => 'PLASTIK SAMPAH 60 X 100 @5pcs', 'unit' => 'PACK'],
            ['kode' => 'D299', 'nama' => 'PLASTIK SAMPAH 90 X 120 @5pcs', 'unit' => 'PACK'],
            ['kode' => 'D300', 'nama' => 'PLASTIK SEGITIGA', 'unit' => 'PACK'],
            ['kode' => 'D301', 'nama' => 'PLASTIK SHEET 20X20 @1kg', 'unit' => 'PACK'],
            ['kode' => 'D302', 'nama' => 'PLASTIK WRAPPING BESAR @20cm', 'unit' => 'ROL'],
            ['kode' => 'D303', 'nama' => 'PLASTIK WRAPPING BESAR @45cm', 'unit' => 'ROL'],
            ['kode' => 'D304', 'nama' => 'Frozen - PUFF PASTRY "EDO" @750gr', 'unit' => 'PACK'],
            ['kode' => 'D305', 'nama' => 'PLASTIK KLIP 8X5', 'unit' => 'PACK'],
            ['kode' => 'D306', 'nama' => 'RICE VINEGAR @600ML', 'unit' => 'BTL'],
            ['kode' => 'D307', 'nama' => 'RINSO @900gr (ungu)', 'unit' => 'PACK'],
            ['kode' => 'D308', 'nama' => 'ROTI TAWAR "LOCO"', 'unit' => 'BKS'],
            ['kode' => 'D309', 'nama' => 'ROTI TAWAR GANDUM "SARI ROTI"', 'unit' => 'BKS'],
            ['kode' => 'D310', 'nama' => 'ROTI TAWAR KUPAS "SARI ROTI"', 'unit' => 'BKS'],
            ['kode' => 'D311', 'nama' => 'ROYCO AYAM @1kg', 'unit' => 'PACK'],
            ['kode' => 'D312', 'nama' => 'ROYCO SAPI @1kg', 'unit' => 'PACK'],
            ['kode' => 'D313', 'nama' => 'RYOTO SP @1kg', 'unit' => 'PACK'],
            ['kode' => 'D346', 'nama' => 'SNACK - KACANG POLONG', 'unit' => 'KG'],
            ['kode' => 'D347', 'nama' => 'SNACK - KERIPIK PISANG', 'unit' => 'KG'],
            ['kode' => 'D348', 'nama' => 'SNACK - KERIPIK SINGKONG', 'unit' => 'KG'],
            ['kode' => 'D349', 'nama' => 'SNACK - KERIPIK UBI', 'unit' => 'KG'],
            ['kode' => 'D350', 'nama' => 'SAUS RAJA RASA @600ml', 'unit' => 'BTL'],
            ['kode' => 'D351', 'nama' => 'SODA WATER "ZODA" @250ml', 'unit' => 'BTL'],
            ['kode' => 'D352', 'nama' => 'SAUS TIRAM "LKK" @770ml', 'unit' => 'BTL'],
            ['kode' => 'D353', 'nama' => 'SOUN CURAH / SJ @500gr', 'unit' => 'PACK'],
            ['kode' => 'D354', 'nama' => 'SOUN VERMICELLI @250gr', 'unit' => 'PACK'],
            ['kode' => 'D355', 'nama' => 'SOUN VERMICELLI @500gr', 'unit' => 'PACK'],
            ['kode' => 'D356', 'nama' => 'SPON BUSA', 'unit' => 'PCS'],
            ['kode' => 'D357', 'nama' => 'SPON KAWAT', 'unit' => 'PCS'],
            ['kode' => 'D358', 'nama' => 'Frozen - SPRING ROLL "TYJ" @20pcs', 'unit' => 'PACK'],
            ['kode' => 'D359', 'nama' => 'SPRITE @1,000ml', 'unit' => 'BTL'],
            ['kode' => 'D360', 'nama' => 'SPRITE @250ml', 'unit' => 'KLG'],
            ['kode' => 'D361', 'nama' => 'STEROFOAM BUBUR @100pcs', 'unit' => 'BAL'],
            ['kode' => 'D362', 'nama' => 'STEROFOAM NASI @100pcs', 'unit' => 'BAL'],
            ['kode' => 'D363', 'nama' => 'SUKADE @250gr', 'unit' => 'PACK'],
            ['kode' => 'D364', 'nama' => 'GARAM KASAR (krosok)', 'unit' => 'KG'],
            ['kode' => 'D365', 'nama' => 'SUNLIGHT @650ml', 'unit' => 'PACK'],
            ['kode' => 'D366', 'nama' => 'SUSHINORI SHEET @10br', 'unit' => 'PACK'],
            ['kode' => 'D367', 'nama' => 'SUSU "DIAMOND" FRESH MILK @1000ml', 'unit' => 'PACK'],
            ['kode' => 'D368', 'nama' => 'SUSU "DIAMOND" UHT PLAIN @1000ml', 'unit' => 'PACK'],
            ['kode' => 'D369', 'nama' => 'SUSU "GREENFIELDS" FRESH MILK @1000ml', 'unit' => 'PACK'],
            ['kode' => 'D370', 'nama' => 'SUSU BERUANG "BEARBRAND" @189ml', 'unit' => 'KLG'],
            ['kode' => 'D371', 'nama' => 'SUSU BUBUK "DANCOW" @800gr', 'unit' => 'PACK'],
            ['kode' => 'D372', 'nama' => 'SUSU BUBUK "DANCOW" SACHET @16x10x27gr', 'unit' => 'CTN'],
            ['kode' => 'D373', 'nama' => 'SUSU BUBUK @500ml', 'unit' => 'PACK'],
            ['kode' => 'D374', 'nama' => 'SIRUP "ABC" ORANGE @460ml', 'unit' => 'BTL'],
            ['kode' => 'D375', 'nama' => 'SUSU EVAPORASI "F&N"', 'unit' => 'KLG'],
            ['kode' => 'D376', 'nama' => 'SUSU KENTAL MANIS COKLAT "BENDERA" @385gr', 'unit' => 'KLG'],
            ['kode' => 'D377', 'nama' => 'SUSU KENTAL MANIS PUTIH "CARNATION" @375gr', 'unit' => 'KLG'],
            ['kode' => 'D378', 'nama' => 'SUSU ULTRA (.....) @125ml x 40pak', 'unit' => 'CTN'],
            ['kode' => 'D379', 'nama' => 'SUSU ULTRA (.....) @200ml x 24pak', 'unit' => 'CTN'],
            ['kode' => 'D380', 'nama' => 'SUSU ULTRA PLAIN @1000ml', 'unit' => 'PACK'],
            ['kode' => 'D381', 'nama' => 'SKM PUTIH "INDOMILK" @370ml', 'unit' => 'CAN'],
            ['kode' => 'D382', 'nama' => 'TAUCO "GAJAH"', 'unit' => 'BTL'],
            ['kode' => 'D314', 'nama' => 'RED KIDNEY BEAN "CIRIO"', 'unit' => 'KLG'],
            ['kode' => 'D315', 'nama' => 'SAMBAL BANGKOK @980gr', 'unit' => 'BTL'],
            ['kode' => 'D316', 'nama' => 'SAN REMO - FETTUCCINE @500gr', 'unit' => 'PACK'],
            ['kode' => 'D317', 'nama' => 'SAN REMO - PANNE PASTA @500gr', 'unit' => 'PACK'],
            ['kode' => 'D318', 'nama' => 'SAN REMO - SPAGHETTI @500gr', 'unit' => 'PACK'],
            ['kode' => 'D319', 'nama' => 'SANTAN "SUN KARA" @1000ml', 'unit' => 'PACK'],
            ['kode' => 'D320', 'nama' => 'SANTAN "SUN KARA" @200ml x 12pak', 'unit' => 'CTN'],
            ['kode' => 'D321', 'nama' => 'SAUS BOLOGNAISE "LAFONTE" @315gr', 'unit' => 'PACK'],
            ['kode' => 'D322', 'nama' => 'SARI MINANG @250gr', 'unit' => 'PACK'],
            ['kode' => 'D323', 'nama' => 'MIKA THWINWALL @25ml x 50pcs', 'unit' => 'PACK'],
            ['kode' => 'D324', 'nama' => 'MIKA THWINWALL @35ml x 50pcs', 'unit' => 'PACK'],
            ['kode' => 'D325', 'nama' => 'SAUS INGGRIS @620ml', 'unit' => 'BTL'],
            ['kode' => 'D326', 'nama' => 'SAUS SAMBAL "DELMONTE" @5,5kg', 'unit' => 'GLN'],
            ['kode' => 'D327', 'nama' => 'SAUS TERIYAKI "SAORI" @1000ml', 'unit' => 'BTL'],
            ['kode' => 'D328', 'nama' => 'SAUS TIRAM "SAORI" @1000ml', 'unit' => 'BTL'],
            ['kode' => 'D329', 'nama' => 'SAUS TIRAM CAP PANDA "LKK" @2,2kg', 'unit' => 'KLG'],
            ['kode' => 'D330', 'nama' => 'SAUS TOMAT "DELMONTE" @5,7kg', 'unit' => 'GLN'],
            ['kode' => 'D331', 'nama' => 'SEDOTAN KOPI / STRER @500pcs', 'unit' => 'PACK'],
            ['kode' => 'D332', 'nama' => 'SEDOTAN PUTIH COVER KERTAS @250btg', 'unit' => 'PACK'],
            ['kode' => 'D333', 'nama' => 'SELAI "CURAH" =RASA ( ... )', 'unit' => 'KG'],
            ['kode' => 'D334', 'nama' => 'SENDOK BEBEK ROYAL @12lsn', 'unit' => 'PACK'],
            ['kode' => 'D335', 'nama' => 'SENDOK MAKAN BENING @25pcs', 'unit' => 'PACK'],
            ['kode' => 'D336', 'nama' => 'SENDOK PUDING BENING 100S', 'unit' => 'PACK'],
            ['kode' => 'D337', 'nama' => 'SEREAL CORN FLAKE (CURAH)', 'unit' => 'KG'],
            ['kode' => 'D338', 'nama' => 'SEREAL KOKO KRUNCH (CURAH)', 'unit' => 'KG'],
            ['kode' => 'D339', 'nama' => 'SIRUP "MARJAN" COCOPANDAN', 'unit' => 'BTL'],
            ['kode' => 'D340', 'nama' => 'SIRUP "MARJAN" GRENADINE', 'unit' => 'BTL'],
            ['kode' => 'D341', 'nama' => 'SIRUP "MARJAN" LYCHEE', 'unit' => 'BTL'],
            ['kode' => 'D342', 'nama' => 'SIRUP "MARJAN" MELON', 'unit' => 'BTL'],
            ['kode' => 'D343', 'nama' => 'SIRUP "MARJAN" ROSE', 'unit' => 'BTL'],
            ['kode' => 'D344', 'nama' => 'SIRUP "MARJAN" STRAWBERRY', 'unit' => 'BTL'],
            ['kode' => 'D383', 'nama' => 'TEH "LIPTON" YELLOW LABEL @100sct', 'unit' => 'PACK'],
            ['kode' => 'D384', 'nama' => 'TEH "SARIWANGI" @9gr x 25sct', 'unit' => 'PACK'],
            ['kode' => 'D385', 'nama' => 'TEH KOTAK JASMINE @24X300ML', 'unit' => 'CTN'],
            ['kode' => 'D386', 'nama' => 'TELUR ASIN MATANG', 'unit' => 'PCS'],
            ['kode' => 'D387', 'nama' => 'TELUR AYAM', 'unit' => 'KG'],
            ['kode' => 'D388', 'nama' => 'TELUR BEBEK MENTAH', 'unit' => 'KG'],
            ['kode' => 'D389', 'nama' => 'TELUR PUYUH MENTAH', 'unit' => 'KG'],
            ['kode' => 'D390', 'nama' => 'TEPUNG "CAKRA" @1kg (KEMASAN)', 'unit' => 'KG'],
            ['kode' => 'D391', 'nama' => 'TEPUNG "CAKRA" @25kg', 'unit' => 'BAL'],
            ['kode' => 'D392', 'nama' => 'TEPUNG "JAWARA" @25kg', 'unit' => 'BAL'],
            ['kode' => 'D393', 'nama' => 'TEPUNG "SEGITIGA BIRU" @1kg (KEMASAN)', 'unit' => 'PACK'],
            ['kode' => 'D394', 'nama' => 'TEPUNG "SEGITIGA BIRU" @25kg', 'unit' => 'BAL'],
            ['kode' => 'D395', 'nama' => 'TEPUNG ACAI CURAH @1kg', 'unit' => 'KG'],
            ['kode' => 'D396', 'nama' => 'TEPUNG BERAS PUTIH @500gr', 'unit' => 'PACK'],
            ['kode' => 'D397', 'nama' => 'TEPUNG BERAS PUTIH @500gr x 20bks', 'unit' => 'CTN'],
            ['kode' => 'D398', 'nama' => 'TEPUNG HUNKWEE 150gr', 'unit' => 'PACK'],
            ['kode' => 'D399', 'nama' => 'TEPUNG KETAN PUTIH @500gr', 'unit' => 'PACK'],
            ['kode' => 'D400', 'nama' => 'TEPUNG KETAN PUTIH @500gr x 20bks', 'unit' => 'CTN'],
            ['kode' => 'D401', 'nama' => 'TEPUNG MAIZENA @750gr', 'unit' => 'PACK'],
            ['kode' => 'D402', 'nama' => 'TEPUNG PANIR/ROTI OREN CURAH @1kg', 'unit' => 'KG'],
            ['kode' => 'D403', 'nama' => 'TEPUNG RAP INSTANT @500gr', 'unit' => 'PACK'],
            ['kode' => 'D404', 'nama' => 'TEPUNG ROTI "MAMASUKA" @1kg', 'unit' => 'PACK'],
            ['kode' => 'D405', 'nama' => 'TEPUNG SAGU "PAK TANI" @500gr', 'unit' => 'PACK'],
            ['kode' => 'D406', 'nama' => 'TEPUNG TERIGU (CURAH) @1KG', 'unit' => 'KG'],
            ['kode' => 'D407', 'nama' => 'TEPUNG MAIZENA @1kg', 'unit' => 'PACK'],
            ['kode' => 'D408', 'nama' => 'TERASI JUHENG', 'unit' => 'PACK'],
            ['kode' => 'D409', 'nama' => 'TISSUE POTONG "GREEN"', 'unit' => 'PACK'],
            ['kode' => 'D410', 'nama' => 'TISSUE COKTAIL "LIVI"', 'unit' => 'PACK'],
            ['kode' => 'D411', 'nama' => 'TISSUE WAJAH', 'unit' => 'PACK'],
            ['kode' => 'D412', 'nama' => 'TOMATO PASTE "DELMONTE" @170gr', 'unit' => 'KLG'],
            ['kode' => 'D413', 'nama' => 'TEPUNG ROTI "MAMASUKA" @500gr', 'unit' => 'PACK'],
            ['kode' => 'D414', 'nama' => 'VLA (SOUH BOEY) @4kg', 'unit' => 'KLG'],
            ['kode' => 'D415', 'nama' => 'TROPICANA SLIMP CLASSIC @100sct', 'unit' => 'PACK'],
            ['kode' => 'D416', 'nama' => 'TUNA CHUNK "AYAM BRAND" @150gr', 'unit' => 'KLG'],
            ['kode' => 'D417', 'nama' => 'TUSUK GIGI COVER @500pcs', 'unit' => 'PACK'],
            ['kode' => 'D418', 'nama' => 'TUSUK GIGI CURAH', 'unit' => 'PACK'],
            ['kode' => 'D419', 'nama' => 'TUSUK SATE "PANDA"', 'unit' => 'PACK'],
            ['kode' => 'D420', 'nama' => 'TUSUK SATE (GEPENG)', 'unit' => 'IKAT'],
            ['kode' => 'D421', 'nama' => 'VANILI CRYSTAL', 'unit' => 'BTL'],
            ['kode' => 'D422', 'nama' => 'VANILLA "ESSENCE"', 'unit' => 'BTL'],
            ['kode' => 'D423', 'nama' => 'WAKAME KERING @500gr', 'unit' => 'PACK'],
            ['kode' => 'D424', 'nama' => 'WIPOL @800ml', 'unit' => 'PACK'],
            ['kode' => 'D425', 'nama' => 'YAKULT @5btl', 'unit' => 'PACK'],
            ['kode' => 'D426', 'nama' => 'YOUGHURT PLAIN @1ltr', 'unit' => 'PAIL'],
            ['kode' => 'D427', 'nama' => 'ABC - TERASI UDANG @20pcs', 'unit' => 'PACK'],
            ['kode' => 'D428', 'nama' => 'AIR MINERAL "PRIMA" @220ml X 48', 'unit' => 'CTN'],
            ['kode' => 'D429', 'nama' => 'AIR MINERAL "PRIMA" @330ml X 24', 'unit' => 'CTN'],
            ['kode' => 'D430', 'nama' => 'AIR MINERAL "PRIMA" @600ml X 24', 'unit' => 'CTN'],
            ['kode' => 'D431', 'nama' => 'AIR MINERAL "VIT" @220ml X 48', 'unit' => 'CTN'],
            ['kode' => 'D432', 'nama' => 'BUMBU RACIK (......)', 'unit' => 'PACK'],
            ['kode' => 'D433', 'nama' => 'BUTTER UNSALTED "ANCHOR" @200gr', 'unit' => 'PACK'],
            ['kode' => 'D434', 'nama' => 'FERIMPAN SACHET (10 X 11gr)', 'unit' => 'PACK'],
            ['kode' => 'D435', 'nama' => 'HAND GLOVE LATEX', 'unit' => 'PACK'],
            ['kode' => 'D436', 'nama' => 'KEJU CHEDDAR "PROCHIZZ" @170gr', 'unit' => 'PACK'],
            ['kode' => 'D437', 'nama' => 'KEJU CHEDDAR PROCIZ GOLD @2kg', 'unit' => 'PACK'],
            ['kode' => 'D438', 'nama' => 'KEJU MOZARELLA "PERFETTO" @250gr', 'unit' => 'PACK'],
            ['kode' => 'D439', 'nama' => 'KEJU MOZARELLA BLOK @2,3kg', 'unit' => 'PACK'],
            ['kode' => 'D440', 'nama' => 'KEJU PARMESAN @80gr', 'unit' => 'BTL'],
            ['kode' => 'D441', 'nama' => 'KERUPUK IKAN LIDAH @5kg', 'unit' => 'BAL'],
            ['kode' => 'D442', 'nama' => 'KIKKOMAN SOYA @1,6L', 'unit' => 'BTL'],
            ['kode' => 'D443', 'nama' => 'KOEPOE2 - PALA BUBUK @65gr', 'unit' => 'BTL'],
            ['kode' => 'D444', 'nama' => 'LADA HITAM BUBUK', 'unit' => 'KG'],
            ['kode' => 'D445', 'nama' => 'LADA PUTIH BUBUK "DESAKU" @100gr', 'unit' => 'RTG'],
            ['kode' => 'D446', 'nama' => 'LADA PUTIH BUBUK (MURNI)', 'unit' => 'KG'],
            ['kode' => 'D447', 'nama' => 'LAFONTE - FETTUCCINE @500gr', 'unit' => 'PACK'],
            ['kode' => 'D448', 'nama' => 'LAFONTE - PANNE PASTA @500gr', 'unit' => 'PACK'],
            ['kode' => 'D449', 'nama' => 'MARGARIN CURAH "SIMAS" @1kg', 'unit' => 'PACK'],
            ['kode' => 'D483', 'nama' => 'SUSU KENTAL MANIS "FRISIAN FLAG" @545gr', 'unit' => 'PACK'],
            ['kode' => 'D484', 'nama' => 'SUSU KENTAL MANIS "FRISIAN FLAG" SACHET', 'unit' => 'PACK'],
            ['kode' => 'D485', 'nama' => 'SUSU UHT COCONUT DELIGHT "FF" @946ml', 'unit' => 'PACK'],
            ['kode' => 'D486', 'nama' => 'TALI RAFIA', 'unit' => 'PCS'],
            ['kode' => 'D487', 'nama' => 'TEH CAP BOTOL @10pcs', 'unit' => 'PACK'],
            ['kode' => 'D488', 'nama' => 'TEH CELUP SOSRO @2gr x 30sct', 'unit' => 'PACK'],
            ['kode' => 'D489', 'nama' => 'TEH KOTAK "SOSRO" @250ml x 24pcs', 'unit' => 'CTN'],
            ['kode' => 'D490', 'nama' => 'TEH SARIWANGI @100 s x 1,85gr', 'unit' => 'PACK'],
            ['kode' => 'D491', 'nama' => 'TEH TUBRUK "CAP BOTOL" @10bks', 'unit' => 'PACK'],
            ['kode' => 'D492', 'nama' => 'THAI TEA @400gr', 'unit' => 'PACK'],
            ['kode' => 'D493', 'nama' => 'TISSUE ROLL @10roli', 'unit' => 'BAL'],
            ['kode' => 'D494', 'nama' => 'TISSUE WAJAH 2ply x 900gr', 'unit' => 'BAL'],
            ['kode' => 'D495', 'nama' => 'TORCH GAS', 'unit' => 'PCS'],
            ['kode' => 'D496', 'nama' => 'TROPICANA SLIM - GULA JAWA @350ml', 'unit' => 'BTL'],
            ['kode' => 'D497', 'nama' => 'TROPICANA SLIM - SIRUP COCOPANDAN @750ml', 'unit' => 'BTL'],
            ['kode' => 'D498', 'nama' => 'TROPICANA SLIM - SELAI STRAWBERRY @375gr', 'unit' => 'BTL'],
            ['kode' => 'D499', 'nama' => 'UDON @800gr', 'unit' => 'PACK'],
            ['kode' => 'D500', 'nama' => 'WHIPPING CREAM "ANCHOR" @1ltr', 'unit' => 'PACK'],
            ['kode' => 'D450', 'nama' => 'MASAKO AYAM @1kg', 'unit' => 'PACK'],
            ['kode' => 'D451', 'nama' => 'MASAKO SAPI @1kg', 'unit' => 'PACK'],
            ['kode' => 'D452', 'nama' => 'MERICA BUBUK "LADAKU"', 'unit' => 'PACK'],
            ['kode' => 'D453', 'nama' => 'MICIN SASA @250gr', 'unit' => 'PACK'],
            ['kode' => 'D454', 'nama' => 'MIE DOROKU @600gr', 'unit' => 'PACK'],
            ['kode' => 'D455', 'nama' => 'MIE TELUR "URAI BURUNG" @200gr', 'unit' => 'PACK'],
            ['kode' => 'D456', 'nama' => 'MIKA 18 X 18', 'unit' => 'PCS'],
            ['kode' => 'D457', 'nama' => 'MIKA THINWALL @100ML X 25pcs', 'unit' => 'SLOP'],
            ['kode' => 'D458', 'nama' => 'MINYAK GORENG "MITRA" 2Ltr', 'unit' => 'CTN'],
            ['kode' => 'D459', 'nama' => 'MINYAK GORENG "MITRA" 2Ltr', 'unit' => 'PACK'],
            ['kode' => 'D460', 'nama' => 'MISOA @400gr', 'unit' => 'PACK'],
            ['kode' => 'D461', 'nama' => 'MIWON @1kg', 'unit' => 'PACK'],
            ['kode' => 'D462', 'nama' => 'MORIN - BLUEBERRY JAM @330gr', 'unit' => 'BTL'],
            ['kode' => 'D463', 'nama' => 'MORIN - PEANUT BUTTER CREAMY JAM @300gr', 'unit' => 'BTL'],
            ['kode' => 'D464', 'nama' => 'MORIN - SELAI STRAWBERRY JAM @330gr', 'unit' => 'BTL'],
            ['kode' => 'D465', 'nama' => 'MORIN - TOPPING CARAMEL @310gr', 'unit' => 'BTL'],
            ['kode' => 'D466', 'nama' => 'MORIN - TOPPING COKLAT @310gr', 'unit' => 'BTL'],
            ['kode' => 'D467', 'nama' => 'MUSTARD YELLOW "MAESTRO" @245gr', 'unit' => 'PACK'],
            ['kode' => 'D468', 'nama' => 'PAPPER BOWL @500ml x 50pcs', 'unit' => 'PACK'],
            ['kode' => 'D469', 'nama' => 'PAPPER BOWL @650ml x 50pcs', 'unit' => 'PACK'],
            ['kode' => 'D470', 'nama' => 'PAPPER BOWL @800ml x 50pcs', 'unit' => 'PACK'],
            ['kode' => 'D471', 'nama' => 'ROTI BURGER @6pcs', 'unit' => 'PACK'],
            ['kode' => 'D472', 'nama' => 'ROTI TAWAR "SARI ROTI" @10pcs', 'unit' => 'PACK'],
            ['kode' => 'D473', 'nama' => 'ROTI TAWAR "SARI ROTI" @15pcs (jumbo)', 'unit' => 'PACK'],
            ['kode' => 'D474', 'nama' => 'SAUS SAMBAL HOT ONE (10 x 1kg)', 'unit' => 'PACK'],
            ['kode' => 'D475', 'nama' => 'SELAI COKLAT "ELMER" @1kg', 'unit' => 'PACK'],
            ['kode' => 'D476', 'nama' => 'SELAI MORIN "SRIKAYA" @800gr', 'unit' => 'PACK'],
            ['kode' => 'D477', 'nama' => 'SIRUP "ABC" LYCHEE @460ml', 'unit' => 'BTL'],
            ['kode' => 'D478', 'nama' => 'SPRINKLE @100gr', 'unit' => 'PACK'],
            ['kode' => 'D479', 'nama' => 'STERNO GEL @5ltr', 'unit' => 'GLN'],
            ['kode' => 'D480', 'nama' => 'SUNLIGHT @210ml', 'unit' => 'PACK'],
            ['kode' => 'D481', 'nama' => 'SUNLIGHT @900ml', 'unit' => 'PACK'],
            ['kode' => 'D482', 'nama' => 'SUSU DAIRY CHAMP', 'unit' => 'KLG'],
        ];

        foreach ($items as $item) {
            KatalogBarang::updateOrCreate(
                ['kode_barang' => $item['kode']],
                [
                    'nama_barang' => $item['nama'],
                    'category_id' => $dryGood->id,
                    'unit_id' => $units[$item['unit']]->id,
                ]
            );
        }

        $this->command->info('✓ ' . count($items) . ' dry good items inserted/updated');
    }
}
