<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\KatalogBarang;
use App\Models\Unit;
use Illuminate\Database\Seeder;

class SayurKatalogSeeder extends Seeder
{
    public function run(): void
    {
        $category = Category::where('nama', 'Sayur')->first();
        if (!$category) {
            $this->command->error('Category "Sayur" not found. Run MasterDataSeeder first.');
            return;
        }

        $unitNames = ['KG', 'PACK', 'IKAT', 'PCS', 'BKS', 'CTN'];
        foreach ($unitNames as $unitName) {
            Unit::firstOrCreate(['nama' => $unitName]);
        }
        $units = Unit::whereIn('nama', $unitNames)->get()->keyBy('nama');
        if (
            !$units->has('KG') ||
            !$units->has('PACK') ||
            !$units->has('IKAT') ||
            !$units->has('PCS') ||
            !$units->has('BKS') ||
            !$units->has('CTN')
        ) {
            $this->command->error('Units "KG", "PACK", "IKAT", "PCS", "BKS", and/or "CTN" not found.');
            return;
        }

        $items = [
            ['kode' => 'V002', 'nama' => 'ASEM KANDIS', 'unit' => 'KG'],
            ['kode' => 'V003', 'nama' => 'BAKSO IKAN @40btr', 'unit' => 'PACK'],
            ['kode' => 'V004', 'nama' => 'BAKSO SAPI SUPER @50btr', 'unit' => 'PACK'],
            ['kode' => 'V005', 'nama' => 'BAWANG BOMBAY', 'unit' => 'KG'],
            ['kode' => 'V006', 'nama' => 'BAWANG PUTIH KUPAS (SLICE)', 'unit' => 'KG'],
            ['kode' => 'V007', 'nama' => 'BAWANG MERAH KUPAS', 'unit' => 'KG'],
            ['kode' => 'V008', 'nama' => 'BAWANG MERAH KUPAS (SLICE)', 'unit' => 'KG'],
            ['kode' => 'V009', 'nama' => 'BAWANG MERAH UTUH', 'unit' => 'KG'],
            ['kode' => 'V010', 'nama' => 'BAWANG PUTIH KUPAS', 'unit' => 'KG'],
            ['kode' => 'V011', 'nama' => 'BAWANG PUTIH UTUH', 'unit' => 'KG'],
            ['kode' => 'V012', 'nama' => 'BELIMBING WULUH/SAYUR', 'unit' => 'KG'],
            ['kode' => 'V013', 'nama' => 'BIJI MELINJO', 'unit' => 'KG'],
            ['kode' => 'V014', 'nama' => 'BIJI SELASIH', 'unit' => 'KG'],
            ['kode' => 'V015', 'nama' => 'BROKOLI UTUH 8-11cm', 'unit' => 'KG'],
            ['kode' => 'V016', 'nama' => 'BROKOLI BERSIH BTG 5-6cm', 'unit' => 'KG'],
            ['kode' => 'V017', 'nama' => 'BROKOLI BERSIH BTG 8-11cm', 'unit' => 'KG'],
            ['kode' => 'V018', 'nama' => 'BUNCIS', 'unit' => 'KG'],
            ['kode' => 'V019', 'nama' => 'BUNCIS (BABY)', 'unit' => 'KG'],
            ['kode' => 'V020', 'nama' => 'CABE HIJAU BESAR UTUH', 'unit' => 'KG'],
            ['kode' => 'V021', 'nama' => 'CABE HIJAU BESAR PETIK', 'unit' => 'KG'],
            ['kode' => 'V022', 'nama' => 'CABE HIJAU KERITING UTUH', 'unit' => 'KG'],
            ['kode' => 'V023', 'nama' => 'CABE HIJAU KERITING PETIK', 'unit' => 'KG'],
            ['kode' => 'V024', 'nama' => 'CABE MERAH BESAR UTUH', 'unit' => 'KG'],
            ['kode' => 'V025', 'nama' => 'CABE MERAH BESAR PETIK', 'unit' => 'KG'],
            ['kode' => 'V026', 'nama' => 'CABE MERAH GILING', 'unit' => 'KG'],
            ['kode' => 'V027', 'nama' => 'CABE MERAH KERING BESAR/TW', 'unit' => 'KG'],
            ['kode' => 'V028', 'nama' => 'CABE MERAH KERING KERITING', 'unit' => 'KG'],
            ['kode' => 'V029', 'nama' => 'CABE MERAH KERITING UTUH', 'unit' => 'KG'],
            ['kode' => 'V030', 'nama' => 'CABE MERAH KERITING PETIK', 'unit' => 'KG'],
            ['kode' => 'V031', 'nama' => 'CABE RAWIT HIJAU UTUH', 'unit' => 'KG'],
            ['kode' => 'V032', 'nama' => 'CABE RAWIT HIJAU PETIK', 'unit' => 'KG'],
            ['kode' => 'V033', 'nama' => 'CABE RAWIT MERAH UTUH', 'unit' => 'KG'],
            ['kode' => 'V034', 'nama' => 'CABE RAWIT MERAH PETIK', 'unit' => 'KG'],
            ['kode' => 'V035', 'nama' => 'CENDOL HIJAU @1,3up', 'unit' => 'PACK'],
            ['kode' => 'V036', 'nama' => 'CINCAU HITAM @1kg', 'unit' => 'PCS'],
            ['kode' => 'V037', 'nama' => 'CIWIS', 'unit' => 'KG'],
            ['kode' => 'V038', 'nama' => 'CUMI ASIN', 'unit' => 'KG'],
            ['kode' => 'V039', 'nama' => 'DAUN BASIL', 'unit' => 'KG'],
            ['kode' => 'V040', 'nama' => 'DAUN BAWANG AKAR', 'unit' => 'KG'],
            ['kode' => 'V041', 'nama' => 'DAUN BAWANG BERSIH', 'unit' => 'KG'],
            ['kode' => 'V042', 'nama' => 'DAUN BAYAM AKAR', 'unit' => 'KG'],
            ['kode' => 'V043', 'nama' => 'DAUN BAYAM AKAR/TP.AKAR', 'unit' => 'IKAT'],
            ['kode' => 'V044', 'nama' => 'DAUN BAYAM TANPA AKAR', 'unit' => 'KG'],
            ['kode' => 'V045', 'nama' => 'DAUN DILL', 'unit' => 'KG'],
            ['kode' => 'V046', 'nama' => 'DAUN HORENZO/BAYAM JEPANG', 'unit' => 'KG'],
            ['kode' => 'V047', 'nama' => 'DAUN JERUK', 'unit' => 'KG'],
            ['kode' => 'V048', 'nama' => 'DAUN KANGKUNG TANPA AKAR', 'unit' => 'KG'],
            ['kode' => 'V049', 'nama' => 'DAUN KANGKUNG TANPA AKAR', 'unit' => 'IKAT'],
            ['kode' => 'V050', 'nama' => 'DAUN KEMANGI', 'unit' => 'KG'],
            ['kode' => 'V051', 'nama' => 'DAUN KEMANGI', 'unit' => 'IKAT'],
            ['kode' => 'V052', 'nama' => 'DAUN KETUMBAR', 'unit' => 'KG'],
            ['kode' => 'V053', 'nama' => 'DAUN KETUMBAR @250gr', 'unit' => 'IKAT'],
            ['kode' => 'V054', 'nama' => 'DAUN KUNYIT', 'unit' => 'KG'],
            ['kode' => 'V055', 'nama' => 'DAUN KUNYIT', 'unit' => 'IKAT'],
            ['kode' => 'V056', 'nama' => 'DAUN MELINJO', 'unit' => 'KG'],
            ['kode' => 'V057', 'nama' => 'DAUN MINT', 'unit' => 'KG'],
            ['kode' => 'V058', 'nama' => 'DAUN MINT @250gr', 'unit' => 'IKAT'],
            ['kode' => 'V059', 'nama' => 'DAUN PAKCOI', 'unit' => 'KG'],
            ['kode' => 'V060', 'nama' => 'DAUN PAKCOI (BABY)', 'unit' => 'KG'],
            ['kode' => 'V061', 'nama' => 'DAUN PANDAN', 'unit' => 'KG'],
            ['kode' => 'V062', 'nama' => 'DAUN PANDAN', 'unit' => 'IKAT'],
            ['kode' => 'V063', 'nama' => 'DAUN PARSLEY', 'unit' => 'KG'],
            ['kode' => 'V064', 'nama' => 'DAUN PARSLEY @250gr', 'unit' => 'IKAT'],
            ['kode' => 'V065', 'nama' => 'DAUN PEPAYA', 'unit' => 'KG'],
            ['kode' => 'V066', 'nama' => 'DAUN PEPAYA', 'unit' => 'IKAT'],
            ['kode' => 'V067', 'nama' => 'DAUN PISANG', 'unit' => 'KG'],
            ['kode' => 'V068', 'nama' => 'DAUN PISANG', 'unit' => 'IKAT'],
            ['kode' => 'V069', 'nama' => 'DAUN SALAM', 'unit' => 'KG'],
            ['kode' => 'V070', 'nama' => 'DAUN SALAM', 'unit' => 'IKAT'],
            ['kode' => 'V071', 'nama' => 'DAUN SELADA AIR', 'unit' => 'KG'],
            ['kode' => 'V072', 'nama' => 'DAUN SELADA AIR @200GR', 'unit' => 'IKAT'],
            ['kode' => 'V073', 'nama' => 'DAUN SELADA HIJAU', 'unit' => 'KG'],
            ['kode' => 'V074', 'nama' => 'DAUN SELADA MERAH', 'unit' => 'KG'],
            ['kode' => 'V075', 'nama' => 'DAUN SELEDRI AKAR', 'unit' => 'KG'],
            ['kode' => 'V076', 'nama' => 'DAUN SELEDRI BERSIH', 'unit' => 'KG'],
            ['kode' => 'V077', 'nama' => 'DAUN SEREH', 'unit' => 'KG'],
            ['kode' => 'V078', 'nama' => 'DAUN SEREH', 'unit' => 'IKAT'],
            ['kode' => 'V079', 'nama' => 'DAUN SINGKONG', 'unit' => 'KG'],
            ['kode' => 'V080', 'nama' => 'DAUN SINGKONG', 'unit' => 'IKAT'],
            ['kode' => 'V081', 'nama' => 'DAUN SINGKONG TANPA BATANG', 'unit' => 'KG'],
            ['kode' => 'V082', 'nama' => 'DAUN SINTRONG', 'unit' => 'KG'],
            ['kode' => 'V083', 'nama' => 'DAUN SINTRONG', 'unit' => 'IKAT'],
            ['kode' => 'V084', 'nama' => 'EBI KERING', 'unit' => 'KG'],
            ['kode' => 'V085', 'nama' => 'ENDIVE/FREESE LETTUCE', 'unit' => 'KG'],
            ['kode' => 'V086', 'nama' => 'IKAN ASIN JAMBAL FILLET', 'unit' => 'KG'],
            ['kode' => 'V087', 'nama' => 'IKAN ASIN KAPASAN', 'unit' => 'KG'],
            ['kode' => 'V088', 'nama' => 'IKAN ASIN KUNIRAN BELAHAN', 'unit' => 'KG'],
            ['kode' => 'V089', 'nama' => 'IKAN ASIN PEDA', 'unit' => 'KG'],
            ['kode' => 'V090', 'nama' => 'IKAN ASIN TERI JENGKI', 'unit' => 'KG'],
            ['kode' => 'V091', 'nama' => 'IKAN ASIN TERI MEDAN', 'unit' => 'KG'],
            ['kode' => 'V092', 'nama' => 'IKAN ASIN TAWAR (uk. Sedang)', 'unit' => 'KG'],
            ['kode' => 'V093', 'nama' => 'JAGUNG MANIS (KULIT)', 'unit' => 'PCS'],
            ['kode' => 'V094', 'nama' => 'JAGUNG MANIS KUPAS', 'unit' => 'KG'],
            ['kode' => 'V095', 'nama' => 'JAGUNG MUDA/SOLENG (BERSIH)', 'unit' => 'KG'],
            ['kode' => 'V096', 'nama' => 'JAHE GILING', 'unit' => 'KG'],
            ['kode' => 'V097', 'nama' => 'JAHE KUPAS', 'unit' => 'KG'],
            ['kode' => 'V098', 'nama' => 'JAHE UTUH', 'unit' => 'KG'],
            ['kode' => 'V099', 'nama' => 'JAMUR CHAMPIGNON', 'unit' => 'KG'],
            ['kode' => 'V100', 'nama' => 'JAMUR ENOKI @100gr', 'unit' => 'PACK'],
            ['kode' => 'V101', 'nama' => 'JAMUR KUPING BASAH', 'unit' => 'KG'],
            ['kode' => 'V102', 'nama' => 'JAMUR MERANG', 'unit' => 'KG'],
            ['kode' => 'V103', 'nama' => 'JAMUR SHIMEJI', 'unit' => 'PACK'],
            ['kode' => 'V104', 'nama' => 'JAMUR SHITAKE', 'unit' => 'KG'],
            ['kode' => 'V105', 'nama' => 'JAMUR TIRAM PUTIH', 'unit' => 'KG'],
            ['kode' => 'V106', 'nama' => 'JERUK LIMO', 'unit' => 'KG'],
            ['kode' => 'V107', 'nama' => 'JERUK NIPIS', 'unit' => 'KG'],
            ['kode' => 'V108', 'nama' => 'JERUK PERES', 'unit' => 'KG'],
            ['kode' => 'V109', 'nama' => 'KACANG MERAH BASAH', 'unit' => 'KG'],
            ['kode' => 'V110', 'nama' => 'KACANG PANJANG', 'unit' => 'KG'],
            ['kode' => 'V111', 'nama' => 'KAILAN BABY', 'unit' => 'KG'],
            ['kode' => 'V112', 'nama' => 'KAILAN BATANG', 'unit' => 'KG'],
            ['kode' => 'V113', 'nama' => 'KAPRI', 'unit' => 'KG'],
            ['kode' => 'V114', 'nama' => 'KECIPIR', 'unit' => 'KG'],
            ['kode' => 'V115', 'nama' => 'KECOMBRANG', 'unit' => 'KG'],
            ['kode' => 'V116', 'nama' => 'KELAPA PARUT', 'unit' => 'PCS'],
            ['kode' => 'V117', 'nama' => 'KELAPA PARUT', 'unit' => 'KG'],
            ['kode' => 'V118', 'nama' => 'KEMBANG KOL UTUH', 'unit' => 'KG'],
            ['kode' => 'V119', 'nama' => 'KEMBANG KOL BERSIH BTG 5-6cm', 'unit' => 'KG'],
            ['kode' => 'V120', 'nama' => 'KENCUR', 'unit' => 'KG'],
            ['kode' => 'V121', 'nama' => 'KENTANG BABY/SIOMAY', 'unit' => 'KG'],
            ['kode' => 'V122', 'nama' => 'KENTANG BESAR', 'unit' => 'KG'],
            ['kode' => 'V123', 'nama' => 'KETIMUN JEPANG/KYURI', 'unit' => 'KG'],
            ['kode' => 'V124', 'nama' => 'KETIMUN LOKAL', 'unit' => 'KG'],
            ['kode' => 'V125', 'nama' => 'KIKIL KULIT', 'unit' => 'KG'],
            ['kode' => 'V126', 'nama' => 'KLUWEK KUPAS', 'unit' => 'KG'],
            ['kode' => 'V127', 'nama' => 'KLUWEK UTUH', 'unit' => 'KG'],
            ['kode' => 'V128', 'nama' => 'KOL PUTIH', 'unit' => 'KG'],
            ['kode' => 'V129', 'nama' => 'KOL UNGU', 'unit' => 'KG'],
            ['kode' => 'V130', 'nama' => 'KOLANG KALING', 'unit' => 'KG'],
            ['kode' => 'V131', 'nama' => 'KUCAI', 'unit' => 'KG'],
            ['kode' => 'V132', 'nama' => 'KULIT LUMPIA @100lbr', 'unit' => 'PACK'],
            ['kode' => 'V133', 'nama' => 'KULIT LUMPIA @50lbr', 'unit' => 'PACK'],
            ['kode' => 'V134', 'nama' => 'KULIT MELINJO', 'unit' => 'KG'],
            ['kode' => 'V135', 'nama' => 'KULIT PANGSIT @50lbr', 'unit' => 'PACK'],
            ['kode' => 'V136', 'nama' => 'KUNYIT KUPAS', 'unit' => 'KG'],
            ['kode' => 'V137', 'nama' => 'KUNYIT UTUH', 'unit' => 'KG'],
            ['kode' => 'V138', 'nama' => 'KUNYIT GILING', 'unit' => 'KG'],
            ['kode' => 'V139', 'nama' => 'KWETIAU BASAH 500GR', 'unit' => 'PACK'],
            ['kode' => 'V140', 'nama' => 'LABU AIR', 'unit' => 'KG'],
            ['kode' => 'V141', 'nama' => 'LABU BUTTERNUT', 'unit' => 'KG'],
            ['kode' => 'V142', 'nama' => 'LABU KABOCA', 'unit' => 'KG'],
            ['kode' => 'V143', 'nama' => 'LABU LALAP', 'unit' => 'KG'],
            ['kode' => 'V144', 'nama' => 'LABU SIAM', 'unit' => 'KG'],
            ['kode' => 'V145', 'nama' => 'LENCAH', 'unit' => 'KG'],
            ['kode' => 'V146', 'nama' => 'LENGKUAS', 'unit' => 'KG'],
            ['kode' => 'V147', 'nama' => 'LENGKUAS GILING', 'unit' => 'KG'],
            ['kode' => 'V148', 'nama' => 'LENGKUAS KUPAS', 'unit' => 'KG'],
            ['kode' => 'V149', 'nama' => 'LETTUCE HEAD', 'unit' => 'KG'],
            ['kode' => 'V150', 'nama' => 'LETTUCE ROMAIN', 'unit' => 'KG'],
            ['kode' => 'V151', 'nama' => 'LOBAK PUTIH', 'unit' => 'KG'],
            ['kode' => 'V152', 'nama' => 'NANGKA MATANG', 'unit' => 'KG'],
            ['kode' => 'V153', 'nama' => 'NANGKA MUDA', 'unit' => 'KG'],
            ['kode' => 'V154', 'nama' => 'ONCOM KUNING', 'unit' => 'KG'],
            ['kode' => 'V155', 'nama' => 'ONCOM KUNING', 'unit' => 'BKS'],
            ['kode' => 'V156', 'nama' => 'OYONG', 'unit' => 'KG'],
            ['kode' => 'V157', 'nama' => 'PAPRIKA HIJAU', 'unit' => 'KG'],
            ['kode' => 'V158', 'nama' => 'PAPRIKA KUNING', 'unit' => 'KG'],
            ['kode' => 'V159', 'nama' => 'PAPRIKA MERAH', 'unit' => 'KG'],
            ['kode' => 'V160', 'nama' => 'PARE', 'unit' => 'KG'],
            ['kode' => 'V161', 'nama' => 'PEPAYA SAYUR', 'unit' => 'KG'],
            ['kode' => 'V162', 'nama' => 'PETAI', 'unit' => 'PCS'],
            ['kode' => 'V163', 'nama' => 'REBUNG IRIS', 'unit' => 'KG'],
            ['kode' => 'V164', 'nama' => 'RED RADISH/LOBAK MERAH BULAT', 'unit' => 'KG'],
            ['kode' => 'V165', 'nama' => 'SAWI ASIN @500gr', 'unit' => 'PACK'],
            ['kode' => 'V166', 'nama' => 'SAWI HIJAU', 'unit' => 'KG'],
            ['kode' => 'V167', 'nama' => 'SAWI PAHIT', 'unit' => 'KG'],
            ['kode' => 'V168', 'nama' => 'SAWI PUTIH', 'unit' => 'KG'],
            ['kode' => 'V169', 'nama' => 'SAYUR ASEM PKT (BESAR)', 'unit' => 'BKS'],
            ['kode' => 'V170', 'nama' => 'SEDAP MALAM', 'unit' => 'KG'],
            ['kode' => 'V171', 'nama' => 'SINGKONG', 'unit' => 'KG'],
            ['kode' => 'V172', 'nama' => 'SINGKONG PARUT', 'unit' => 'KG'],
            ['kode' => 'V173', 'nama' => 'TAHU GUNTING KOTAK', 'unit' => 'PCS'],
            ['kode' => 'V174', 'nama' => 'TAHU GUNTING SEGITIGA', 'unit' => 'PCS'],
            ['kode' => 'V175', 'nama' => 'TAHU IRIS', 'unit' => 'PCS'],
            ['kode' => 'V176', 'nama' => 'TAHU JAMBE', 'unit' => 'PCS'],
            ['kode' => 'V177', 'nama' => 'TAHU BANDUNG KUNING', 'unit' => 'PCS'],
            ['kode' => 'V178', 'nama' => 'TAHU PONG', 'unit' => 'PCS'],
            ['kode' => 'V179', 'nama' => 'TAHU PUTIH CINA', 'unit' => 'PCS'],
            ['kode' => 'V180', 'nama' => 'TAHU PUTIH CINA (JUMBO)', 'unit' => 'PCS'],
            ['kode' => 'V181', 'nama' => 'TAPE KETAN HITAM', 'unit' => 'KG'],
            ['kode' => 'V182', 'nama' => 'TAPE SINGKONG', 'unit' => 'KG'],
            ['kode' => 'V183', 'nama' => 'TEMPE BESAR PLASTIK', 'unit' => 'PACK'],
            ['kode' => 'V184', 'nama' => 'TEMPE PLASTIK', 'unit' => 'KG'],
            ['kode' => 'V185', 'nama' => 'TEMPE KECIL PLASTIK', 'unit' => 'PACK'],
            ['kode' => 'V186', 'nama' => 'TEMU KUNCI', 'unit' => 'KG'],
            ['kode' => 'V187', 'nama' => 'TERONG LALAP', 'unit' => 'KG'],
            ['kode' => 'V188', 'nama' => 'TERONG UNGU', 'unit' => 'KG'],
            ['kode' => 'V189', 'nama' => 'TOGE BANDUNG', 'unit' => 'KG'],
            ['kode' => 'V190', 'nama' => 'TOGE PANJANG', 'unit' => 'KG'],
            ['kode' => 'V191', 'nama' => 'TOGE PENDEK', 'unit' => 'KG'],
            ['kode' => 'V192', 'nama' => 'TOMAT CHERRY MERAH (curah)', 'unit' => 'KG'],
            ['kode' => 'V193', 'nama' => 'TOMAT HIJAU', 'unit' => 'KG'],
            ['kode' => 'V194', 'nama' => 'TOMAT MERAH BESAR', 'unit' => 'KG'],
            ['kode' => 'V195', 'nama' => 'TOMAT MERAH KECIL', 'unit' => 'KG'],
            ['kode' => 'V196', 'nama' => 'TONGCAY @250gr', 'unit' => 'PACK'],
            ['kode' => 'V197', 'nama' => 'UBI MERAH', 'unit' => 'KG'],
            ['kode' => 'V198', 'nama' => 'UBI PUTIH', 'unit' => 'KG'],
            ['kode' => 'V199', 'nama' => 'UBI UNGU', 'unit' => 'KG'],
            ['kode' => 'V200', 'nama' => 'WORTEL IMPORT', 'unit' => 'KG'],
            ['kode' => 'V201', 'nama' => 'WORTEL LOKAL SUPER', 'unit' => 'KG'],
            ['kode' => 'V202', 'nama' => 'WORTEL LOKAL KECIL', 'unit' => 'KG'],
            ['kode' => 'V203', 'nama' => 'ZUKINI', 'unit' => 'KG'],
            ['kode' => 'V204', 'nama' => 'CAKWE', 'unit' => 'PCS'],
            ['kode' => 'V205', 'nama' => 'JENGKOL KULIT', 'unit' => 'KG'],
            ['kode' => 'V206', 'nama' => 'JENGKOL REBUS', 'unit' => 'KG'],
            ['kode' => 'V207', 'nama' => 'KACANG TANAH (KULIT)', 'unit' => 'KG'],
            ['kode' => 'V208', 'nama' => 'LONTONG', 'unit' => 'PCS'],
            ['kode' => 'V209', 'nama' => 'MIE HOKKIEN', 'unit' => 'KG'],
            ['kode' => 'V210', 'nama' => 'MIE KUNING BASAH', 'unit' => 'KG'],
            ['kode' => 'V211', 'nama' => 'TOFU', 'unit' => 'PCS'],
            ['kode' => 'V212', 'nama' => 'TOFU @10PCS', 'unit' => 'PACK'],
            ['kode' => 'V213', 'nama' => 'UBI CILEMBU MENTAH', 'unit' => 'KG'],
            ['kode' => 'V214', 'nama' => 'ASPARAGUS FRESH', 'unit' => 'KG'],
            ['kode' => 'V215', 'nama' => 'DAUN GENJER', 'unit' => 'IKAT'],
            ['kode' => 'V216', 'nama' => 'DAUN GENJER', 'unit' => 'KG'],
            ['kode' => 'V217', 'nama' => 'DAUN ROSEMARY FRESH', 'unit' => 'KG'],
            ['kode' => 'V218', 'nama' => 'MIE AYAM KERING @1kg', 'unit' => 'PACK'],
            ['kode' => 'V219', 'nama' => 'BUAH SUKUN', 'unit' => 'KG'],
            ['kode' => 'V220', 'nama' => 'CELERY STICK', 'unit' => 'KG'],
            ['kode' => 'V221', 'nama' => 'TOMAT CHERRY MERAH (super) @250gr', 'unit' => 'PACK'],
            ['kode' => 'V222', 'nama' => 'KACANG EDAMAME (fresh)', 'unit' => 'KG'],
            ['kode' => 'V223', 'nama' => 'RUMPUT LAUT PUTIH (es)', 'unit' => 'KG'],
            ['kode' => 'V224', 'nama' => 'JAGUNG MUDA/SOLENG (BERSIH) (kecil)', 'unit' => 'KG'],
            ['kode' => 'V225', 'nama' => 'CABE RAWIT HIJAU UTUH (kecil)', 'unit' => 'KG'],
            ['kode' => 'V226', 'nama' => 'CABE RAWIT HIJAU PETIK (kecil)', 'unit' => 'KG'],
            ['kode' => 'V227', 'nama' => 'BOMBAY UNGU/MERAH', 'unit' => 'KG'],
            ['kode' => 'V228', 'nama' => 'KENTANG RENDANG', 'unit' => 'KG'],
            ['kode' => 'V229', 'nama' => 'DAUN TESPONG', 'unit' => 'KG'],
            ['kode' => 'V230', 'nama' => 'KAPUR SIRIH', 'unit' => 'BKS'],
            ['kode' => 'V231', 'nama' => 'TOMAT RAMPAI', 'unit' => 'KG'],
            ['kode' => 'V232', 'nama' => 'BAKSO SAPI \"ESSEM\" @50btr', 'unit' => 'PACK'],
            ['kode' => 'V233', 'nama' => 'BUMBU RENDANG GILING', 'unit' => 'KG'],
            ['kode' => 'V234', 'nama' => 'DAUN KANGKUNG (akar)', 'unit' => 'IKAT'],
            ['kode' => 'V235', 'nama' => 'IKAN ASIN PETEK', 'unit' => 'KG'],
            ['kode' => 'V236', 'nama' => 'IKAN PINDANG', 'unit' => 'KG'],
            ['kode' => 'V237', 'nama' => 'SINGKONG (kupas bersih)', 'unit' => 'KG'],
            ['kode' => 'V238', 'nama' => 'WORTEL IMPORT BERASTAGI @10kg', 'unit' => 'CTN'],
        ];

        foreach ($items as $item) {
            KatalogBarang::updateOrCreate(
                ['kode_barang' => $item['kode']],
                [
                    'nama_barang' => $item['nama'],
                    'category_id' => $category->id,
                    'unit_id' => $units[$item['unit']]->id,
                ]
            );
        }

        $this->command->info('✓ ' . count($items) . ' sayur items inserted/updated');
    }
}
